/**
 * Style Presets Module
 * Extracted from eventHandlers.js
 */

import {
  getSettings,
  updateSetting,
  saveSettings,
} from "../../services/state.js"
import { renderBookmarks } from "../bookmarks.js"

export const STYLE_PRESETS = {
  clean: {
    bookmarkLayout: "default",
    bookmarkItemStyle: "default",
    bookmarkHideText: false,
    bookmarkHideBg: true,
    bookmarkMacosHover: false,
    bookmarkFontSize: 10,
    bookmarkIconSize: 42,
    bookmarkGap: 10,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 0,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 0,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 14,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 14,
    bookmarkShadowBlur: 6,
    musicBarStyle: "minimal",
    musicPlayerSkin: "white-blur",
  },
  dock: {
    bookmarkLayout: "taskbar",
    bookmarkLayoutBgStyle: "default",
    bookmarkItemStyle: "default",
    bookmarkHideText: true,
    bookmarkHideBg: false,
    bookmarkMacosHover: true,
    bookmarkFontSize: 10,
    bookmarkIconSize: 46,
    bookmarkGap: 8,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 92,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 0,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 13,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 22,
    bookmarkShadowBlur: 10,
    musicBarStyle: "pill",
    musicPlayerSkin: "white-blur",
  },
  macos: {
    bookmarkLayout: "taskbar",
    bookmarkLayoutBgStyle: "default",
    bookmarkItemStyle: "default",
    bookmarkHideText: true,
    bookmarkHideBg: false,
    bookmarkMacosHover: true,
    bookmarkFontSize: 10,
    bookmarkIconSize: 52,
    bookmarkGap: 10,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 88,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 0,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 13,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 24,
    bookmarkShadowBlur: 14,
    musicBarStyle: "apple",
    musicPlayerSkin: "white-blur",
  },
  glass: {
    bookmarkLayout: "default",
    bookmarkItemStyle: "default",
    bookmarkHideText: false,
    bookmarkHideBg: false,
    bookmarkMacosHover: false,
    bookmarkFontSize: 10,
    bookmarkIconSize: 42,
    bookmarkGap: 10,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 28,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 22,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 14,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 18,
    bookmarkShadowBlur: 12,
    musicBarStyle: "vinyl",
    musicPlayerSkin: "white-blur",
  },
  compact: {
    bookmarkLayout: "taskbar-left",
    bookmarkLayoutBgStyle: "hidden",
    bookmarkItemStyle: "default",
    bookmarkHideText: true,
    bookmarkHideBg: true,
    bookmarkMacosHover: false,
    bookmarkFontSize: 9,
    bookmarkIconSize: 34,
    bookmarkGap: 4,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 0,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 0,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 12,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 16,
    bookmarkShadowBlur: 6,
    musicBarStyle: "minimal",
    musicPlayerSkin: "default",
  },
  sidebar: {
    bookmarkLayout: "sidebar",
    bookmarkLayoutBgStyle: "default",
    bookmarkItemStyle: "default",
    bookmarkHideText: false,
    bookmarkHideBg: false,
    bookmarkMacosHover: false,
    bookmarkFontSize: 10,
    bookmarkIconSize: 38,
    bookmarkGap: 7,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 56,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 0,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 14,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 18,
    bookmarkShadowBlur: 8,
    musicBarStyle: "sidebar",
    musicPlayerSkin: "white-blur",
  },
  neon: {
    bookmarkLayout: "default",
    bookmarkItemStyle: "default",
    bookmarkHideText: false,
    bookmarkHideBg: false,
    bookmarkMacosHover: false,
    bookmarkFontSize: 11,
    bookmarkIconSize: 44,
    bookmarkGap: 12,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 34,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 18,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 14,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 24,
    bookmarkShadowBlur: 10,
    musicBarStyle: "neon",
    musicPlayerSkin: "white-blur",
  },
  terminal: {
    bookmarkLayout: "sidebar",
    bookmarkLayoutBgStyle: "default",
    bookmarkItemStyle: "default",
    bookmarkHideText: false,
    bookmarkHideBg: false,
    bookmarkMacosHover: false,
    bookmarkFontSize: 10,
    bookmarkIconSize: 36,
    bookmarkGap: 7,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 18,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 10,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 13,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 18,
    bookmarkShadowBlur: 8,
    musicBarStyle: "terminal",
    musicPlayerSkin: "default",
  },
  cassette: {
    bookmarkLayout: "default",
    bookmarkItemStyle: "default",
    bookmarkHideText: false,
    bookmarkHideBg: false,
    bookmarkMacosHover: false,
    bookmarkFontSize: 10,
    bookmarkIconSize: 44,
    bookmarkGap: 11,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 52,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 18,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 14,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 18,
    bookmarkShadowBlur: 10,
    musicBarStyle: "cassette",
    musicPlayerSkin: "white-blur",
  },
  cozy: {
    bookmarkLayout: "default",
    bookmarkItemStyle: "default",
    bookmarkHideText: false,
    bookmarkHideBg: false,
    bookmarkMacosHover: true,
    bookmarkFontSize: 11,
    bookmarkIconSize: 46,
    bookmarkGap: 12,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 64,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 24,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 14,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 20,
    bookmarkShadowBlur: 12,
    musicBarStyle: "minimal",
    musicPlayerSkin: "white-blur",
  },
  vision: {
    bookmarkLayout: "taskbar",
    bookmarkLayoutBgStyle: "glass",
    bookmarkItemStyle: "glass",
    bookmarkHideText: true,
    bookmarkHideBg: false,
    bookmarkMacosHover: true,
    bookmarkFontSize: 10,
    bookmarkIconSize: 48,
    bookmarkGap: 12,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 30,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 10,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: true,
    bookmarkGroupFontSize: 13,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 30,
    bookmarkShadowBlur: 16,
    musicBarStyle: "pill",
    musicPlayerSkin: "glass",
  },
  material: {
    bookmarkLayout: "default",
    bookmarkLayoutBgStyle: "default",
    bookmarkItemStyle: "card",
    bookmarkHideText: false,
    bookmarkHideBg: false,
    bookmarkMacosHover: false,
    bookmarkFontSize: 11,
    bookmarkIconSize: 40,
    bookmarkGap: 16,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 100,
    bookmarkGroupBgColor: "#f3f4f6",
    bookmarkGroupBgOpacity: 100,
    bookmarkGroupTextColor: "#1f2937",
    bookmarkGroupAutoTextContrast: false,
    bookmarkGroupFontSize: 14,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 12,
    bookmarkShadowBlur: 8,
    musicBarStyle: "minimal",
    musicPlayerSkin: "solid-light",
  },
  aura: {
    bookmarkLayout: "sidebar",
    bookmarkLayoutBgStyle: "glass",
    bookmarkItemStyle: "card",
    bookmarkHideText: false,
    bookmarkHideBg: false,
    bookmarkMacosHover: true,
    bookmarkFontSize: 12,
    bookmarkIconSize: 36,
    bookmarkGap: 8,
    bookmarkTextColor: null,
    bookmarkBgColor: "#ffffff",
    bookmarkBgOpacity: 15,
    bookmarkGroupBgColor: "#ffffff",
    bookmarkGroupBgOpacity: 10,
    bookmarkGroupTextColor: null,
    bookmarkGroupAutoTextContrast: true,
    bookmarkGroupFontSize: 15,
    bookmarkShadowColor: "#000000",
    bookmarkShadowOpacity: 40,
    bookmarkShadowBlur: 24,
    musicBarStyle: "sidebar",
    musicPlayerSkin: "black-blur",
  },
}
export const INTERFACE_STYLE_KEYS = new Set([
  "bookmarkLayout",
  "bookmarkLayoutBgStyle",
  "bookmarkLayoutBgColor",
  "bookmarkItemStyle",
  "bookmarkHideText",
  "bookmarkHideBg",
  "bookmarkHideScrollbar",
  "bookmarkMacosHover",
  "bookmarkFontSize",
  "bookmarkIconSize",
  "bookmarkGap",
  "bookmarkTextColor",
  "bookmarkBgColor",
  "bookmarkBgOpacity",
  "bookmarkGroupBgColor",
  "bookmarkGroupBgOpacity",
  "bookmarkGroupTextColor",
  "bookmarkGroupAutoTextContrast",
  "bookmarkGroupFontSize",
  "bookmarkGroupBorderRadius",
  "bookmarkShadowColor",
  "bookmarkShadowOpacity",
  "bookmarkShadowBlur",
  "musicBarStyle",
  "musicPlayerSkin",
  "musicPlayerUseDefaultColor",
])

export const setStylePresetActive = (presetId) => {
  document
    .querySelectorAll(".style-preset-btn[data-style-preset]")
    .forEach((btn) => {
      btn.classList.toggle("active", btn.dataset.stylePreset === presetId)
    })
}

export const markInterfaceStyleCustom = (key) => {
  if (key && !INTERFACE_STYLE_KEYS.has(key)) return
  if (getSettings().interfaceStylePreset !== "custom") {
    updateSetting("interfaceStylePreset", "custom")
  }
  setStylePresetActive("custom")
}

export const dispatchSettingsUpdated = (key, value) => {
  window.dispatchEvent(
    new CustomEvent("settingsUpdated", {
      detail: { key, value },
    }),
  )
}

export const applyInterfaceStylePreset = (presetId, { updateSettingsInputs, applySettings } = {}) => {
  let preset = STYLE_PRESETS[presetId]
  if (!preset && presetId && presetId.startsWith("user-style-")) {
    const userStyles = getSettings().userStyles || []
    const found = userStyles.find((s) => s.id === presetId)
    if (found) {
      preset = found.snapshot
    }
  }
  if (!preset) return

  Object.entries(preset).forEach(([key, value]) => updateSetting(key, value))
  updateSetting("interfaceStylePreset", presetId)
  saveSettings(true)
  updateSettingsInputs()
  applySettings()
  renderBookmarks()
  setStylePresetActive(presetId)
  if (preset.musicBarStyle !== undefined) {
    dispatchSettingsUpdated("musicBarStyle", preset.musicBarStyle)
  }
  if (preset.musicPlayerSkin !== undefined) {
    dispatchSettingsUpdated("musicPlayerSkin", preset.musicPlayerSkin)
  }
}

