export const VISUAL_THEME_KEYS = [
  "theme",
  "accentColor",
  "sidebarBg",
  "panelBg",
  "glassBg",
  "glassBorder",
  "glassEdge",
  "font",
  "clockFont",
  "clockColor",
  "dateColor",
  "customTitleColor",
  "customTitleFontSize",
  "customTitleLetterSpacing",
  "clockDateStrokeColor",
  "clockDateStrokeWidth",
  "clockDateStrokeTarget",
]

export const VISUAL_EFFECT_KEYS = [
  "effect",
  "performanceMode",
  "starColor",
  "meteorColor",
  "meteorAngle",
  "meteorFullColor",
  "auraColor",
  "northernLightsColor",
  "northernLightsStyle",
  "northernLightsBrightness",
  "hackerColor",
  "pixelCubesColor",
  "sakuraColor",
  "snowfallColor",
  "fallingLeavesSkin",
  "sunbeamColor",
  "sunbeamAngle",
  "bubbleColor",
  "rainHDColor",
  "stormRainColor",
  "wavyLinesColor",
  "oceanWaveColor",
  "oceanWavePosition",
  "cloudDriftColor",
  "shinyColor",
  "lineShinyColor",
  "nintendoPixelColor",
  "crtScanColor",
  "crtScanFrequency",
  "crtScanAngle",
  "crtScanDensity",
  "crtGamma",
  "crtBackgroundColor",
  "retroGameType",
  "retroGameColor",
  "cursorTrailColor",
  "cursorTrailStyle",
  "cursorTrailClickExplosion",
  "cursorTrailRandomColor",
  "flashlightColor",
  "flashlightSize",
  "flashlightOpacity",
  "gridScanColor",
  "gridSpacing",
  "gridPerspective",
  "plantGrowthColor",
  "oceanFishColor",
  "floatingLinesColor",
  "floatingLinesAngle",
  "pixelWeatherStyle",
  "pixelWeatherResolution",
  "pixelWeatherSpeed",
  "pixelWeatherSize",
  "pixelWeatherDensity",
  "pixelSnowHQColor",
  "pixelSnowHQFlakeSize",
  "pixelSnowHQMinFlakeSize",
  "pixelSnowHQPixelResolution",
  "pixelSnowHQSpeed",
  "pixelSnowHQDepthFade",
  "pixelSnowHQFarPlane",
  "pixelSnowHQBrightness",
  "pixelSnowHQGamma",
  "pixelSnowHQDensity",
  "pixelSnowHQVariant",
  "pixelSnowHQDirection",
]

export function pickSettings(settings, keys) {
  return keys.reduce((payload, key) => {
    if (settings[key] !== undefined) payload[key] = settings[key]
    return payload
  }, {})
}
